#!/usr/bin/env bash
# Wires Serena to this checkout: ocaml-lsp for src/, the Haxe language server for std/.
# Run it in a new checkout or worktree and after adding a file to std/, then restart Serena.
# Requires opam (with the libpcre2, zlib and mbedtls development packages), node, npm and curl.
#
# Downloads and builds are shared between checkouts, in ${XDG_CACHE_HOME:-~/.cache}/haxe-dev:
#   compiler/<build key>      the published build of this checkout's build key, linked as .haxe
#   language-server/<commit>  vshaxe/haxe-language-server, built from source
#   opam/<OCaml version>      the switch linked as _opam when the checkout has none
set -euo pipefail
cd "$(dirname "$0")/.."

REPO=GeTechG/haxe
# The published vshaxe (2.34.2) needs `--wait stdio`, which Haxe 5 dropped; this commit talks to the
# compiler over a socket.
LS_COMMIT=e865ce6ffa9299960d558728948691b7a5e9d4a2
OCAML_VERSION=${OCAML_VERSION:-5.3.0}
CACHE=${XDG_CACHE_HOME:-$HOME/.cache}/haxe-dev
LOCAL=.serena/project.local.yml
MARK="# GENERATED by extra/setup-serena.sh"
export OPAMYES=1

die() { echo "setup-serena: $*" >&2; exit 1; }

[ "$(uname -sm)" = "Linux x86_64" ] || die "the published compiler builds are Linux x86_64 only"
command -v opam >/dev/null || die "opam not found: install opam, libpcre2-dev, zlib1g-dev and libmbedtls-dev"
for tool in node npm curl; do
	command -v "$tool" >/dev/null || die "$tool not found"
done
if [ -f "$LOCAL" ] && grep -qv '^\s*\(#\|$\)' "$LOCAL" && ! grep -qF "$MARK" "$LOCAL"; then
	die "$LOCAL holds your own settings; move it aside and run again"
fi

# The compiler: the build of the build key, by the rule of .github/workflows/binaries.yml.
mapfile -t infra < <(sed -e '/^#/d' -e '/^$/d' -e '/^extra\/build-linux\.sh$/d' \
	-e 's/^/:(top,exclude,literal)/' .github/infra-paths)
key=$(git log -1 --format=%H HEAD -- . "${infra[@]}")
compiler=$CACHE/compiler/$key
if [ ! -x "$compiler/haxe" ]; then
	url=https://github.com/$REPO/releases/download/builds/haxe-linux64-$key.tar.gz
	mkdir -p "$CACHE/compiler"
	tmp=$(mktemp -d "$compiler.tmp.XXXXXX")
	trap 'rm -rf "$tmp"' EXIT
	code=$(curl -sSL -o "$tmp/build.tar.gz" -w '%{http_code}' "$url") || die "cannot download $url"
	[ "$code" != 404 ] || die "build key $key has no published build yet (see the Binaries workflow); no other build is used"
	[ "$code" = 200 ] || die "cannot download $url: HTTP $code"
	tar -xzf "$tmp/build.tar.gz" -C "$tmp"
	rm "$tmp/build.tar.gz"
	mv -T "$tmp" "$compiler" 2>/dev/null || true # a concurrent run finished first: same key, same build
	[ -x "$compiler/haxe" ] || die "no compiler in $compiler"
fi
ln -sfn "$compiler" .haxe

server=$CACHE/language-server/$LS_COMMIT
if [ ! -f "$server/bin/server.js" ]; then
	mkdir -p "$CACHE/language-server"
	tmp=$(mktemp -d "$server.tmp.XXXXXX")
	trap 'rm -rf "$tmp"' EXIT
	git init -q "$tmp"
	git -C "$tmp" fetch -q --depth 1 https://github.com/vshaxe/haxe-language-server "$LS_COMMIT"
	git -C "$tmp" checkout -q FETCH_HEAD
	(cd "$tmp" && npm ci --silent && npx lix run vshaxe-build -t language-server >/dev/null)
	[ -f "$tmp/bin/server.js" ] || die "the language server build left no bin/server.js"
	mv -T "$tmp" "$server" 2>/dev/null || true
fi

# The display configuration. A display server that is given no modules types nothing and answers a
# reference lookup in part, so every module of std/ that types under the target is named; the modules of
# other platforms do not, and are left out.
mkdir -p .serena
export HAXE_STD_PATH=$PWD/std
{
	echo "$MARK: do not edit, run it again."
	echo "--interp"
	(cd std && find . -name '*.hx' ! -name import.hx ! -path '*/_std/*') |
		sed -e 's|^\./||' -e 's|\.hx$||' -e 's|/|.|g' |
		xargs -P "$(nproc)" -n 1 sh -c '"$0" --interp --no-output "$1" >/dev/null 2>&1 && echo "$1"; :' .haxe/haxe |
		sort
} > .serena/display.hxml
.haxe/haxe .serena/display.hxml --no-output || die ".serena/display.hxml does not compile"

# OCaml: ocaml-lsp runs in the switch opam finds from the checkout, with the compiler's dependencies.
if [ ! -e _opam ]; then
	switch=$CACHE/opam/$OCAML_VERSION
	if [ ! -d "$switch/_opam" ]; then
		[ -d "${OPAMROOT:-$HOME/.opam}" ] || opam init --bare --no-setup
		mkdir -p "$switch"
		opam switch create "$switch" "$OCAML_VERSION" --no-install
	fi
	ln -s "$switch/_opam" _opam
fi
deps=$(mktemp -d)
trap 'rm -rf "$deps"' EXIT
# conf-neko is only needed to build haxelib
grep -v conf-neko haxe.opam > "$deps/haxe-deps.opam"
opam install "$deps/haxe-deps.opam" --deps-only --assume-depexts
opam install ocaml-lsp-server
# Cross-file references read this index. Serena builds it too, but gives up after two minutes; the release
# profile is the Makefile's (.mcp.json and .codex/config.toml set it for Serena), dev stops at a warning.
opam exec -- dune build --profile release @ocaml-index

# .haxe and _opam are untracked; ignoring them here keeps .gitignore, a code path, as it is upstream.
exclude=$(git rev-parse --git-path info/exclude)
mkdir -p "$(dirname "$exclude")"
for path in /.haxe /_opam; do
	grep -qxF "$path" "$exclude" 2>/dev/null || echo "$path" >> "$exclude"
done

# Serena overwrites project.local.yml when it has to generate a missing project.yml.
[ -f .serena/project.yml ] || printf 'language_servers:\n- ocaml\n- haxe\n' > .serena/project.yml
# haxePath is not read by the server: the compiler is the first haxe on PATH.
cat > "$LOCAL" <<YAML
$MARK: do not edit, run it again.
language_servers:
- ocaml
- haxe
ls_specific_settings:
  haxe:
    buildFile: .serena/display.hxml
    ls_base_cmd: ["sh", "-c", 'PATH="\$PWD/.haxe:\$PATH" HAXE_STD_PATH="\$PWD/std" exec node "$server/bin/server.js"']
    ls_args: []
YAML
echo "setup-serena: compiler $key, $(grep -c '^[A-Za-z]' .serena/display.hxml) modules; restart Serena"
